### ISSUE TITLE
error: Package `libvala-0.28' not found in specified Vala API directories or GObject-Introspection GIR directories

### ISSUE THREAD

**Issue by igarcez** [inizan-yannick/afrodite#5]
sudo apt-get install libvala-0.28-dev                                 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libvala-0.28-dev is already the newest version.

When trying to run make, on elementary freya 64bits

**Comment by inizan-yannick** [comment]
your version of valac is different. please run "valac --version" to check version.
or run valac-0.28
